### ISSUE TITLE
Flexible spellcaster repertiore spells don't show up in heightened slots

### ISSUE THREAD

**Issue by robinsving** [Saibot393/enhancedcombathud-pf2e#53]
**Background**
When having a repertoire with Flexible spellcaster, all spells are signature spells

**Problem**
When opening a certain spell rank in the Argon HUD for spells, you only get the spells added from that rank
![image](https://github.com/user-attachments/assets/f1c3c1fe-fbb0-4d05-9e9e-5542e4a6bca8)

This despite a lot of spells are taken due to their heightenable effect
![image](https://github.com/user-attachments/assets/cc1ffcce-1cb8-48bc-9315-2ff64f0cdbe4)

**Expected behaviour**
Spells from lower ranks should show up in higher slots, for flexible spellcasters

**Comment by Saibot393** [comment]
I will look into it

**Comment by Saibot393** [comment]
I just remebered, the way i implemented flexible spell casting is as follows:
The spells are only shown in their "base level" section. When you cast them and could in theory cast them at a higher level a window will show up (see screenshot) which allows you to select the level the spell is cast at.
![image](https://github.com/user-attachments/assets/ef9e6cdf-0d4d-4ce3-bd35-abd5680a6bd3)
The reason i did it this way instead of adding the spells to all following rank section is, that i felt like it would easily blow up the higher ranks, making the ui a bit unwieldy.

**Comment by robinsving** [comment]
I see it now. That does make a lot of sense, and is likely the easier one to implement than more custom options
Thanks for the reply!
